{% set name = "google-cloud-alloydb" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_alloydb-{{ version }}.tar.gz
  sha256: 5011a2c34b2075a613fa435d14da46327a8c6e13f2e03faaf9880b756b5a29b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # use more constrained proto-plus for python >= 3.13 to stay noarch
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev

test:
  imports:
    - google.cloud.alloydb
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-alloydb
  summary: Google Cloud Alloydb API client library
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-alloydb

extra:
  recipe-maintainers:
    - xylar
